name: CD
on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io

jobs:
  
    create_docker_image:
        runs-on: ubuntu-latest
        outputs:
          version: ${{steps.Image.outputs.version}}
          image_name: ${{steps.Image.outputs.image_name}}
        
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write

        steps:
            - name: Image Name Info
              id: Image
              run: |
                date=$(echo "$(date +'%Y%m%d')")
                echo "date=$date" >> $GITHUB_OUTPUT
                version=$(echo "v$date.${{ github.run_number }}")
                echo "version=$version" >> $GITHUB_OUTPUT
                image_name=$(echo "${{ github.event.repository.name }}-${{ github.ref_name }}:$version" | tr '[:upper:]' '[:lower:]' | tr / - )
                echo "image_name=$image_name" >> $GITHUB_OUTPUT
                echo "Image name is: $image_name"
                
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: |
                docker build -t ${{steps.Image.outputs.image_name}} .

            - name: Log in to the Container registry
              uses: docker/login-action@v3.2.0

              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Docker Tag & Push to GHCR
              run: |
                repo_owner=$(echo '${{github.repository_owner}}')
                repo_owner_lowercase=$(echo $repo_owner | tr '[:upper:]' '[:lower:]')
                docker tag ${{steps.Image.outputs.image_name}} ${{env.REGISTRY}}/$repo_owner_lowercase/${{steps.Image.outputs.image_name}}
                docker push ${{env.REGISTRY}}/$repo_owner_lowercase/${{steps.Image.outputs.image_name}}
                

    release_GH:
      runs-on: ubuntu-latest
      needs: create_docker_image

      permissions:
        contents: write

      steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            token: ${{secrets.GITHUB_TOKEN}}
        
        - name: Configure Git User
          run: |
              git config --global user.name "Release"

        - name: Create a Tag GH
          run: git tag -a ${{needs.create_docker_image.outputs.version}} -m "New release ${{needs.create_docker_image.outputs.date}}"

        - name: Git Push to Repo
          run: git push  https://github.com/${{github.repository}} --tags ${{needs.create_docker_image.outputs.version}}
        
        - name: Create Release name
          id: release_tag
          run: |
            release_name_tag=$(echo "${{ github.ref_name }}-${{needs.create_docker_image.outputs.version}}"| tr '[:upper:]' '[:lower:]' | tr / - ) 
            echo "release_name_tag=$release_name_tag" >> $GITHUB_OUTPUT

        - name: Create new release
          uses: softprops/action-gh-release@v2.2.1
          with:
            release_name: "Release ${{needs.create_docker_image.outputs.date}}"
            files: ./*
            token: ${{secrets.GITHUB_TOKEN}}
            tag_name: ${{steps.release_tag.outputs.release_name_tag}}